services:
  srv:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./saved:/opt/palworld/Pal/Saved
    ports:
      - "8211:8211/udp"
    command:
      - ./PalServer.sh
      - -useperfthreads
      - -NoAsyncLoadingThread
      - -UseMultithreadForDS
      - -publiclobby
